spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAVT7FZ27L3XSHZ3VM
  secretKey: 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
  bucketName: yuta.okuda.ac.hitachi.com

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
